
--select * from TCAD_CONTROLE_FUNCIONARIO
--where FUNCIONARIO_Id = 13
--order by DATA_APONTAMENTO desc


--SELECT 
--	b.Id, 
--	b.NOME,
--	CASE WHEN b.TRABALHA_SABADO = 1 THEN 'SIM' ELSE 'NÃO' END
--FROM TCAD_CONTROLE_FUNCIONARIO a
--LEFT JOIN TCAD_FUNCIONARIO b
--	ON a.FUNCIONARIO_Id = b.Id
--WHERE FUNCIONARIO_Id = 13
--	AND YEAR(data_apontamento) = 2024
--	AND MONTH(data_apontamento) = 2
--ORDER BY DATA_APONTAMENTO DESC



SELECT
	CAST(DATA_APONTAMENTO AS DATE) DataApontamento,
	YEAR(DATA_APONTAMENTO) ano,
	MONTH(DATA_APONTAMENTO) mes, 
	CONVERT(VARCHAR(5), CAST(b.HORA_INICIO AS TIME), 108) AS EntradaPlanejada,
	CONVERT(VARCHAR(5), CAST(a.DATA_ENTRADA AS TIME), 108) AS EntradaReal,
	DATEDIFF(MINUTE, CAST(a.DATA_ENTRADA AS TIME), CAST(b.HORA_INICIO AS TIME)) AS DifEntrada,
	CONVERT(VARCHAR(5), CAST(b.HORA_FIM AS TIME), 108) AS SaidaPlanejada,
	CONVERT(VARCHAR(5), CAST(a.DATA_SAIDA AS TIME), 108) AS SaidaReal,
	DATEDIFF(MINUTE, CAST(b.HORA_FIM AS TIME), CAST(a.DATA_SAIDA AS TIME)) AS DifSaida
FROM TCAD_CONTROLE_FUNCIONARIO a
LEFT JOIN TCAD_FUNCIONARIO b
	ON a.FUNCIONARIO_Id = b.Id
WHERE 1=1
	AND FUNCIONARIO_Id = 13
	AND (
		ABS(
			DATEDIFF(
				MINUTE, CAST(b.HORA_INICIO AS TIME), CAST(a.DATA_ENTRADA AS TIME)
			)
		) > 5 OR 
		ABS(
			DATEDIFF(
				MINUTE, CAST(b.HORA_FIM AS TIME), CAST(a.DATA_SAIDA AS TIME)
			)
		) > 5
	)
ORDER BY DATA_APONTAMENTO DESC
