
--select * from TCAD_CONTROLE_FUNCIONARIO
--where FUNCIONARIO_Id = 13
--order by DATA_APONTAMENTO desc


--SELECT DISTINCT  -- overview
--	b.Id, 
--	b.NOME as Name,
--	cast(b.HORA_INICIO as time) as StartTime,
--	cast(b.HORA_FIM as time) as EndTime,
--	CASE WHEN b.TRABALHA_SABADO = 1 THEN 'SIM' ELSE 'NÃO' END as WorksSaturday
--FROM TCAD_CONTROLE_FUNCIONARIO a
--LEFT JOIN TCAD_FUNCIONARIO b
--	ON a.FUNCIONARIO_Id = b.Id
--WHERE FUNCIONARIO_Id = 13
--	AND DATA_APONTAMENTO BETWEEN '2024-2-1' AND '2024-2-18'
-- + funcionario ativo


	SELECT -- atrasos
		Funcionario_Id,
		nome, max(hora_inicio) a,
		--CAST(DATA_APONTAMENTO AS DATE) DataApontamento,
		--CONVERT(VARCHAR(5), CAST(b.HORA_INICIO AS TIME), 108) AS EntradaPlanejada,
		--CONVERT(VARCHAR(5), CAST(a.DATA_ENTRADA AS TIME), 108) AS EntradaReal,
		--DATEDIFF(MINUTE, CAST(b.HORA_INICIO AS TIME), CAST(a.DATA_ENTRADA AS TIME)) AS DifEntrada
		COUNT(*) as contagem_atrasos,
		SUM(DATEDIFF(MINUTE, CAST(b.HORA_INICIO AS TIME), CAST(a.DATA_ENTRADA AS TIME))) as minutos_atraso
	FROM TCAD_CONTROLE_FUNCIONARIO a
	LEFT JOIN TCAD_FUNCIONARIO b
		ON a.FUNCIONARIO_Id = b.Id
	WHERE 1=1
		--AND FUNCIONARIO_Id = 15
		AND (
				DATEDIFF(
					MINUTE, CAST(b.HORA_INICIO AS TIME), CAST(a.DATA_ENTRADA AS TIME)
				) >= 1
			) 
		AND DATA_APONTAMENTO BETWEEN '2024-2-1' AND '2024-2-18'
	GROUP BY FUNCIONARIO_Id, nome
----ORDER BY DATA_APONTAMENTO DESC





SELECT -- extra
	Funcionario_Id,
	--CAST(DATA_APONTAMENTO AS DATE) DataApontamento,
	--CONVERT(VARCHAR(5), CAST(b.HORA_FIM AS TIME), 108) AS SaidaPlanejada,
	--CONVERT(VARCHAR(5), CAST(a.DATA_SAIDA AS TIME), 108) AS SaidaReal,
	--DATEDIFF(MINUTE, CAST(b.HORA_FIM AS TIME), CAST(a.DATA_SAIDA AS TIME)) AS DifEntrada
	SUM(DATEDIFF(MINUTE, CAST(b.HORA_FIM AS TIME), CAST(a.DATA_SAIDA AS TIME)))
FROM TCAD_CONTROLE_FUNCIONARIO a
LEFT JOIN TCAD_FUNCIONARIO b
	ON a.FUNCIONARIO_Id = b.Id
WHERE 1=1
	--AND FUNCIONARIO_Id = 13
	AND (
			DATEDIFF(
				MINUTE, CAST(b.HORA_FIM AS TIME), CAST(a.DATA_SAIDA AS TIME)
			) >= 1
		) 
	AND DATA_APONTAMENTO BETWEEN '2024-2-1' AND '2024-2-18'
GROUP BY FUNCIONARIO_Id





SELECT -- extra
	Funcionario_Id,
	--CAST(DATA_APONTAMENTO AS DATE) DataApontamento,
	--CONVERT(VARCHAR(5), CAST(b.HORA_FIM AS TIME), 108) AS SaidaPlanejada,
	--CONVERT(VARCHAR(5), CAST(a.DATA_SAIDA AS TIME), 108) AS SaidaReal,
	--DATEDIFF(MINUTE, CAST(b.HORA_FIM AS TIME), CAST(a.DATA_SAIDA AS TIME)) AS DifEntrada
	--SUM(DATEDIFF(MINUTE, CAST(b.HORA_FIM AS TIME), CAST(a.DATA_SAIDA AS TIME)))
FROM TCAD_CONTROLE_FUNCIONARIO a
LEFT JOIN TCAD_FUNCIONARIO b
	ON a.FUNCIONARIO_Id = b.Id
WHERE 1=1
	--AND FUNCIONARIO_Id = 13
	AND (
			DATEDIFF(
				MINUTE, CAST(b.HORA_FIM AS TIME), CAST(a.DATA_SAIDA AS TIME)
			) >= 1
		) 
	AND DATA_APONTAMENTO BETWEEN '2024-2-1' AND '2024-2-18'
--GROUP BY FUNCIONARIO_Id