name: Build Docker image

env:
  ENV ASPNETCORE_ENVIRONMENT: Production

on:
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/${{github.repository_owner}}/${{github.repository}}:latest
          docker push ghcr.io/${{github.repository_owner}}/${{github.repository}}:latest
